### ISSUE TITLE
docker grpc crash segmentation fault after query

### ISSUE THREAD

**Issue by shotor** [tihu-nlp/tihu#41]
Hi @b00f, love the work you put into this

I'm building a small os react-native client and trying to run tihu as a grpc service through docker.

It builds fine and starts up, but when doing a query it crashes with:

```
Segmentation fault (core dumped)
```

My code: https://github.com/shotor/tihu-grpc-js/blob/master/index.js

Am I doing something wrong?

**Comment by b00f** [comment]
Hi @shotor. I always though my github-id is weird, your is funnier! 
Your project sounds great. I will check it and update you here soon. 

Thanks for using Tihu.

**Comment by b00f** [comment]
Hi again. I checked your code. The problem is passing invalid voice to Tihu. Currently tihu supporting following voices:

```
TIHU_VOICE_MBROLA_MALE    = 0
TIHU_VOICE_MBROLA_FEMALE  = 1
TIHU_VOICE_ESPEAK_MALE    = 2
TIHU_VOICE_ESPEAK_FEMALE  = 3
```

To fix the issue you can change the [voice id](https://github.com/shotor/tihu-grpc-js/blob/41ecd1b45cc2f99cebd34dea5571b94345d66770/index.js#L21) to zero(0)

The best solution is defining an enum for voice in protobuf. please go ahead if you have time to update the tihu.prto. Here is a reference might help:
https://developers.google.com/protocol-buffers/docs/proto3#enum

**Comment by b00f** [comment]
It is bad of me that I didn't check if the voice is out of the range! sorry

**Comment by shotor** [comment]
No worries, it works now! Thanks for checking the issue. I made a PR to type the voice parameter

I had to guess at the audio options, frequence, sample rate etc. because I couldn't find them in the repo. These are the options that worked for me:

```
sampleRate: 22050,
channels: 1,
bitDepth: 16,
```
Are these correct? And are they the same for all the voices? Maybe it's good to add these to the readme

**Comment by b00f** [comment]
Yup. Those option are correct. Let me explain more:
Sample rate is fixed in Tihu and it is always 22050 Hz. Tihu is using [src](http://www.mega-nerd.com/libsamplerate/index.html) for resampling audio data. look [here](https://github.com/tihu-nlp/tihu/blob/ec6d67e98b8443372a8dda595349deb10c8544fc/src/synthesis/synthesizer.cpp#L50).

However the method name is not so nice. Maybe `ParseSample` make more sence here thatn `PlaySample` 

About volume and pitches, the tihu itself has the apis to adjust them: [here](https://github.com/tihu-nlp/tihu/blob/ec6d67e98b8443372a8dda595349deb10c8544fc/src/tihu.h#L38)
Maybe we need to add these params to the proto file.
